version: "3.5"
services:
  eduquest:
    image: mysql:8.3.0
    container_name: eduquest
    environment:
      MYSQL_DATABASE: 'eduquest'
      MYSQL_USER: 'testuser'
      MYSQL_PASSWORD: 'pw'
      MYSQL_ROOT_PASSWORD: 'rpw'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:rw
      - ./ddl:/docker-entrypoint-initdb.d
volumes:
  eduquest:
